## NLP - 1 - Bag of words

In [1]:
import nltk
import numpy as np
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [2]:
stop_words = set(stopwords.words("english"))

In [3]:
def tokenized_text(sentence):
    words = nltk.word_tokenize(sentence)
    
    cleaned_text = [w.lower() for w in words if w not in stop_words]
    
    return cleaned_text

In [4]:
def sorted_token(sentences):
    
    words = []
    
    for sentence in sentences:
        
        w = tokenized_text(sentence)
        words.extend(w)
        
    words = sorted(list(set(words)))
    return words

In [8]:
def bag_of_words(sentence, words):
    
    sentence_words = tokenized_text(sentence)
    
    # frequency word count
    
    bag = np.zeros(len(words))
    
    for sw in sentence_words:
        for i, word in enumerate(words):
            if word == sw:
                bag[i] += 1
    
    return np.array(bag)

In [6]:
corpus = ["Joe went to the store",
         "Joe wants to buy a dining set",
         "Joe met John at the store",
         "Joe and John are best friends",
         ]

In [7]:
vocabulary = sorted_token(corpus)

print(vocabulary)

['best', 'buy', 'dining', 'friends', 'joe', 'john', 'met', 'set', 'store', 'wants', 'went']


In [12]:
bag_of_words("Joe went to the store", vocabulary)

array([0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1.])

In [13]:
bag_of_words("Joe wants to buy a dining set", vocabulary)

array([0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0.])

In [14]:
bag_of_words("Joe met John at the store",vocabulary)

array([0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0.])

In [15]:
bag_of_words("Joe and John are best friends",vocabulary)

array([1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0.])