## Bag of words

In [11]:
import nltk
import numpy as np
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [12]:
stop_words = set(stopwords.words("english"))

In [13]:
def extract_words(sentence):
    words = nltk.word_tokenize(sentence)
    
    cleaned_text = [w.lower() for w in words if w not in stop_words]
    
    return cleaned_text

In [14]:
def tokenize_sentences(sentences):
    
    words = []
    
    for sentence in sentences:
        
        w = extract_words(sentence)
        words.extend(w)
        
    words = sorted(list(set(words)))
    return words

In [15]:
def bagofwords(sentence, words):
    
    sentence_words = extract_words(sentence)
    
    # frequency word count
    
    bag = np.zeros(len(words))
    
    for sw in sentence_words:
        for i, word in enumerate(words):
            if word == sw:
                bag[i] += 1
    
    return np.array(bag)

In [16]:
corpus = ["John saw the train",
         "The train was late",
         "Max and Rob took the bus",
         "I looked for Max and Rob at the bus station",
         "Max and Rob arrived at the bus station early but waited until noon for the bus"]

In [19]:
vocabulary = tokenize_sentences(corpus)

print(vocabulary)

['arrived', 'bus', 'early', 'i', 'john', 'late', 'looked', 'max', 'noon', 'rob', 'saw', 'station', 'the', 'took', 'train', 'waited']


In [20]:
bagofwords("Max and Rob took the bus", vocabulary)

array([0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0.])

In [21]:
bagofwords("Max and Rob arrived at the bus station early but waited until noon for the bus", vocabulary)

array([1., 2., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1.])

In [22]:
bagofwords("John saw the train",vocabulary)

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.])